// Hand-written mirrors of the Prisma models, used purely as explicit type
// annotations in a few spots where TypeScript's inference needs a hand.
// These are structurally compatible with the real `@prisma/client` types
// generated by `prisma generate` (see prisma/schema.prisma) — they exist so
// this file type-checks even before `prisma generate` has run.

export interface IndicationRow {
  id: string;
  name: string;
  searchTerm: string;
  isDefault: boolean;
  createdAt: Date;
}

export interface CompoundRow {
  id: string;
  name: string;
  aliases: string[];
  isDefault: boolean;
  createdAt: Date;
}

export interface RefreshLogRow {
  id: string;
  startedAt: Date;
  finishedAt: Date | null;
  status: string;
  trialsScanned: number;
  changesFound: number;
  newTrials: number;
  errorMessage: string | null;
}

export interface TrialRow {
  nctId: string;
  briefTitle: string;
  officialTitle: string | null;
  overallStatus: string;
  studyType: string | null;
  phases: string[];
  enrollmentCount: number | null;
  enrollmentType: string | null;
  startDate: string | null;
  primaryCompletionDate: string | null;
  completionDate: string | null;
  lastUpdatePosted: string | null;
  sponsorName: string | null;
  conditions: string[];
  interventions: unknown;
  locationsSummary: string | null;
  briefSummary: string | null;
  raw: unknown;
  matchedIndications: string[];
  matchedCompounds: string[];
  firstSeenAt: Date;
  lastCheckedAt: Date;
  lastChangedAt: Date | null;
  isNewSinceLastRefresh: boolean;
  changedInLastRefresh: boolean;
}
